### ISSUE TITLE
Which version of UNIGNN are you using?

### ISSUE THREAD

**Issue by bokveizen** [tbh-98/WCE-GNN#1]
Dear authors,

Thank you for your great work!
May I ask which version of UNIGNN you are using?
Based on the description in the paper, am I supposed to find it at https://github.com/jianhao2016/AllSet/blob/main/src/models.py?

Thank you for your help in advance.

**Comment by tbh-98** [comment]
Thank you for your interest in our work. We use UNIGCNII; the details can be found in our Appendix B. Yes, you can access it at https://github.com/jianhao2016/AllSet/blob/main/src/models.py.

**Comment by bokveizen** [comment]
Thanks a lot!
